<?php

/**
 * This is the model base class for the table "users_apps".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersApps".
 *
 * Columns in table "users_apps" available as properties of the model,
 * followed by relations of table "users_apps" available as properties of the model.
 *
 * @property integer $id
 * @property integer $apps_id
 * @property integer $users_id
 *
 * @property Users $users
 * @property Apps $apps
 */
abstract class BaseUsersApps extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users_apps';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Aplicación Usuario|Aplicaciones Usuario', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('apps_id, users_id', 'required'),
			array('apps_id, users_id', 'numerical', 'integerOnly'=>true),
			array('id, apps_id, users_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'users' => array(self::BELONGS_TO, 'Users', 'users_id'),
			'apps' => array(self::BELONGS_TO, 'Apps', 'apps_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'apps_id' => null,
			'users_id' => null,
			'users' => null,
			'apps' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('apps_id', $this->apps_id);
		$criteria->compare('users_id', $this->users_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}