<?php

/**
 * This is the model base class for the table "estilos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Estilos".
 *
 * Columns in table "estilos" available as properties of the model,
 * followed by relations of table "estilos" available as properties of the model.
 *
 * @property integer $id_estilos
 * @property string $valor
 * @property integer $stylesheets_id
 * @property integer $tipos_estilos_id
 *
 * @property Stylesheets $stylesheets
 * @property TiposEstilos $tiposEstilos
 */
abstract class BaseEstilos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'estilos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Estilo|Estilos', $n);
	}

	public static function representingColumn() {
		return 'valor';
	}

	public function rules() {
		return array(
			array('valor, stylesheets_id, tipos_estilos_id', 'required'),
			array('stylesheets_id, tipos_estilos_id', 'numerical', 'integerOnly'=>true),
			array('valor', 'length', 'max'=>100),
			array('id_estilos, valor, stylesheets_id, tipos_estilos_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'stylesheets' => array(self::BELONGS_TO, 'Stylesheets', 'stylesheets_id'),
			'tiposEstilos' => array(self::BELONGS_TO, 'TiposEstilos', 'tipos_estilos_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_estilos' => Yii::t('app', 'Id Estilos'),
			'valor' => Yii::t('app', 'Valor'),
			'stylesheets_id' => null,
			'tipos_estilos_id' => null,
			'stylesheets' => null,
			'tiposEstilos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_estilos', $this->id_estilos);
		$criteria->compare('valor', $this->valor, true);
		$criteria->compare('stylesheets_id', $this->stylesheets_id);
		$criteria->compare('tipos_estilos_id', $this->tipos_estilos_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}