<?php

/**
 * This is the model base class for the table "tipos_estilos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TiposEstilos".
 *
 * Columns in table "tipos_estilos" available as properties of the model,
 * followed by relations of table "tipos_estilos" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 *
 * @property Estilos[] $estiloses
 */
abstract class BaseTiposEstilos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipos_estilos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tipo Estilo|Tipos Estilos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre', 'length', 'max'=>100),
			array('descripcion', 'length', 'max'=>255),
			array('descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, descripcion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'estiloses' => array(self::HAS_MANY, 'Estilos', 'tipos_estilos_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'estiloses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}