<?php

/**
 * This is the model base class for the table "stylesheets".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Stylesheets".
 *
 * Columns in table "stylesheets" available as properties of the model,
 * followed by relations of table "stylesheets" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 *
 * @property Estilos[] $estiloses
 * @property EstilosLineas[] $estilosLineases
 * @property StylesheetsApps[] $stylesheetsApps
 */
abstract class BaseStylesheets extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'stylesheets';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Stylesheet|Stylesheets', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('nombre', 'length', 'max'=>45),
			array('id, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'estiloses' => array(self::HAS_MANY, 'Estilos', 'stylesheets_id'),
			'estilosLineases' => array(self::HAS_MANY, 'EstilosLineas', 'stylesheets_id'),
			'stylesheetsApps' => array(self::HAS_MANY, 'StylesheetsApps', 'stylesheets_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'estiloses' => null,
			'estilosLineases' => null,
			'stylesheetsApps' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}