<?php

/**
 * This is the model base class for the table "stylesheets_apps".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StylesheetsApps".
 *
 * Columns in table "stylesheets_apps" available as properties of the model,
 * followed by relations of table "stylesheets_apps" available as properties of the model.
 *
 * @property integer $id
 * @property integer $stylesheets_id
 * @property integer $apps_id
 *
 * @property Stylesheets $stylesheets
 * @property Apps $apps
 */
abstract class BaseStylesheetsApps extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'stylesheets_apps';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Stylesheet de Aplicación|Stylesheets de Aplicaciones', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('stylesheets_id, apps_id', 'required'),
			array('stylesheets_id, apps_id', 'numerical', 'integerOnly'=>true),
			array('id, stylesheets_id, apps_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'stylesheets' => array(self::BELONGS_TO, 'Stylesheets', 'stylesheets_id'),
			'apps' => array(self::BELONGS_TO, 'Apps', 'apps_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'stylesheets_id' => null,
			'apps_id' => null,
			'stylesheets' => null,
			'apps' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('stylesheets_id', $this->stylesheets_id);
		$criteria->compare('apps_id', $this->apps_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}